# -*- coding: utf-8 -*-
"""internsavy task 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izoRhbjVkj7s5igJQAExXbMcppeLXxm0
"""

import numpy as np, pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

customers = pd.read_csv('/content/Mall_Customers (1).csv')

customers.head()

"""**Exploring the Data**"""

# See the distribution of gender to recognize different distributions
sns.countplot(x='Gender', data=customers);
plt.title('Distribution of Gender');

# Create a histogram of ages
customers.hist('Age', bins=35);
plt.title('Distribution of Age');
plt.xlabel('Age');

plt.hist('Age', data=customers[customers['Gender'] == 'Male'], alpha=0.5, label='Male');
plt.hist('Age', data=customers[customers['Gender'] == 'Female'], alpha=0.5, label='Female');
plt.title('Distribution of Age by Gender');
plt.xlabel('Age');
plt.legend();

customers.hist('Annual Income (k$)');
plt.title('Annual Income Distribution in Thousands of Dollars');
plt.xlabel('Thousands of Dollars');

# Histogram of income by gender
plt.hist('Annual Income (k$)', data=customers[customers['Gender'] == 'Male'], alpha=0.5, label='Male');
plt.hist('Annual Income (k$)', data=customers[customers['Gender'] == 'Female'], alpha=0.5, label='Female');
plt.title('Distribution of Income by Gender');
plt.xlabel('Income (Thousands of Dollars)');
plt.legend();

# Create data sets by gender to save time in the future since gender seems to significantly impact other variables
male_customers = customers[customers['Gender'] == 'Male']
female_customers = customers[customers['Gender'] == 'Female']

# Print the average spending score for men and women
print(male_customers['Spending Score (1-100)'].mean())
print(female_customers['Spending Score (1-100)'].mean())

sns.scatterplot(x='Age', y='Annual Income (k$)', hue='Gender', data=customers);
plt.title('Age to Income, Colored by Gender');

sns.heatmap(customers.corr(), annot=True)

sns.scatterplot(x='Age', y='Spending Score (1-100)', hue='Gender', data=customers);
plt.title('Age to Spending Score, Colored by Gender');

sns.heatmap(female_customers.corr(), annot=True);
plt.title('Correlation Heatmap - Female');

sns.lmplot(x='Age', y='Spending Score (1-100)', data=female_customers);
plt.title('Age to Spending Score, Female Only');

sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', hue='Gender', data=customers);
plt.title('Annual Income to Spending Score, Colored by Gender');